name: 'RUIBAL: Apóstol de los Andes'
favicon: null
layout_spectrum: 0.0006838210392743349
typography_spectrum: 0.26507677137851715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.31477272091433406
  lightness: 0.16508703888393939
  saturation: 0.5662496113218367
  rhythmicContrast: 0.3238347126170993
purpose: []
